#!/usr/bin/env bash

# history
HISTSIZE=1000000
HISTFILE=/dev/null

# disable freeze
stty -ixon

# completers
complete -C "$HOME"/python/bin/aws_completer aws

# PS1

RED='\[\e[1;31m\]'
GREEN='\[\e[1;32m\]'
PROMPT='\u@\h'
TEXT='\[\e[0m\]'

# initialize shell depth
printf -v _shell_depth_str '%*s' "$((SHLVL-1))" ''
_shell_depth_str=${_shell_depth_str:+${_shell_depth_str// />} }

# ps
PS1="$_shell_depth_str$GREEN$PROMPT$RED\$(parse_git_branch_and_add_brackets) : \w\$ "$TEXT

# unset shell depth
unset _shell_depth_str
