#!/bin/bash

# vundle
if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
    echo "vundle doesn't exist, cloning vundle"
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    vim +PluginInstall +qall
fi

#xrdb ~/.Xresources

# doge
dogecoin(){
doge --shibe "$(find /usr/local/lib/python2.7/dist-packages/doge/static/ -type f | sort -R  | head -1 | xargs basename)"
}

hmm(){
echo "
⠰⡿⠿⠛⠛⠻⠿⣷
⠀⠀⠀⠀⠀⠀⣀⣄⡀⠀⠀⠀⠀⢀⣀⣀⣤⣄⣀⡀
⠀⠀⠀⠀⠀⢸⣿⣿⣷⠀⠀⠀⠀⠛⠛⣿⣿⣿⡛⠿⠷
⠀⠀⠀⠀⠀⠘⠿⠿⠋⠀⠀⠀⠀⠀⠀⣿⣿⣿⠇
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠁

⠀⠀⠀⠀⣿⣷⣄⠀⢶⣶⣷⣶⣶⣤⣀
⠀⠀⠀⠀⣿⣿⣿⠀⠀⠀⠀⠀⠈⠙⠻⠗
⠀⠀⠀⣰⣿⣿⣿⠀⠀⠀⠀⢀⣀⣠⣤⣴⣶⡄
⠀⣠⣾⣿⣿⣿⣥⣶⣶⣿⣿⣿⣿⣿⠿⠿⠛⠃
⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄
⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡁
⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁
⠀⠀⠛⢿⣿⣿⣿⣿⣿⣿⡿⠟
⠀⠀⠀⠀⠀⠉⠉⠉
"
}

rms(){
echo "
I'd just like to interject for a moment.  What you're referring to as Linux,
is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux.
Linux is not an operating system unto itself, but rather another free component
of a fully functioning GNU system made useful by the GNU corelibs, shell
utilities and vital system components comprising a full OS as defined by POSIX.

Many computer users run a modified version of the GNU system every day,
without realizing it.  Through a peculiar turn of events, the version of GNU
which is widely used today is often called 'Linux', and many of its users are
not aware that it is basically the GNU system, developed by the GNU Project.

There really is a Linux, and these people are using it, but it is just a
part of the system they use.  Linux is the kernel: the program in the system
that allocates the machine's resources to the other programs that you run.
The kernel is an essential part of an operating system, but useless by itself;
it can only function in the context of a complete operating system.  Linux is
normally used in combination with the GNU operating system: the whole system
is basically GNU with Linux added, or GNU/Linux.  All the so-called 'Linux'
distributions are really distributions of GNU/Linux.

WWWWWWWWWWMWN0kl..... .'',;:;';dKXNWWWWWWWWWWWWW
WWWWWWWWWWWNOl,.... . .:dk000KOo'c0XWWWWWWWWWWWWW
WWWWWWWMWNXx:.. .,:oxO0KKKXXKKk';kKNWWWWWWWWWWW
WWWWWWWWWXKo.. . ;oxOO00KKKKKKKXk.;dOKNWWWWWWWWW
WWWWWWWWX0d;. .'cdkOOOO00KKKKKXXc.;lxKNWWWWWWWW
WWWWWWNOo;.. .,:ooc;;;:dk0Oo:co0x..':kXWWWWWWWW
WWWWWKko:'. .;clc;;',:,,dKc,;;okK;..,x0NWWWWWWW
WWWWXko;'. 'codlcllcl;cOXOccoO0X0. .cOXNWWWWWW
WWWNKo;.. 'cxkkkxxdookOKXX0O0XNN;..,xKXWWWWWW
WWNK0c'. ..cdxxxkOkdcolxO00XNWMWd..:dKWWWWWWM
WNNXOc,. .';lodxkOOko:',':k0NMWXd',ld0NNWWWWW
NNX0oc,. ...';codxdoc,'..':xXW0x:,,xx0XWWWWWW
NXO:,. ....',cc:;,,,;';;lkOd;,'.ldOKWWWWWW
Oko'.. .. ...''''',;;cl:ol;'',cOKKXNNWWWW
l;.... . . .........';,;coxkkO0kdkOKXNWW
;.. . . .. .....'',cxOKKK0kxxk0xdxxOXWW
...........','... .'cldxxkO0KKKO0OddddxOO00loOXWW
.'''....',',,,;,,''',oO000000OOOkxdodooldoccxkkkoxKWW
'.. ..,,,,;::::clldxkkkkkkkkxxxdoolcclllcllcodkKNWWWW
...';.,,',,:;clox0Oxdxxxxxxddooollc;,:lcc:cclxXNNWWWW
"
}

random_cowsay(){
fortune | cowsay -f "$(find /usr/share/cowsay/cows/ | shuf -n1 | xargs basename)"
}
